# Generated by Django 5.1.4 on 2024-12-24 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0002_rename_image_id_image2item_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image2item',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.music'),
        ),
        migrations.AlterField(
            model_name='image2item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurant'),
        ),
        migrations.AlterField(
            model_name='image2item',
            name='rfood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurantfood'),
        ),
        migrations.AlterField(
            model_name='image2item',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.travel'),
        ),
        migrations.AlterField(
            model_name='tag2item',
            name='music',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.music'),
        ),
        migrations.AlterField(
            model_name='tag2item',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurant'),
        ),
        migrations.AlterField(
            model_name='tag2item',
            name='rfood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurantfood'),
        ),
        migrations.AlterField(
            model_name='tag2item',
            name='travel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.travel'),
        ),
    ]
