# Generated by Django 5.1.4 on 2025-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0008_alter_item_address_alter_item_artist_alter_item_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_range',
            field=models.CharField(choices=[('', None), ('$', '$'), ('$$', '$$'), ('$$$', '$$$'), ('$$$$', '$$$$'), ('$$$$$', '$$$$$')], default=''),
        ),
    ]
