# Generated by Django 5.1.4 on 2025-02-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0017_rename_image2item_itemimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimages',
            options={'ordering': ['item']},
        ),
    ]
