# Generated by Django 5.1.4 on 2025-02-26 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0020_alter_image_options_image_item_delete_itemimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag2item',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='item',
        ),
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cuisine',
        ),
        migrations.RemoveField(
            model_name='item',
            name='gmap_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_url',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='item',
            name='music_meta',
        ),
        migrations.RemoveField(
            model_name='item',
            name='music_source',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_range',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Dining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('gmap_url', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('price_range', models.CharField(blank=True, default='', max_length=200)),
                ('cuisine', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.item')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('cuisine', models.CharField(blank=True, default='', max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.item')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(blank=True, default='', max_length=200)),
                ('genre', models.CharField(blank=True, default='', max_length=200)),
                ('source', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.item')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('gmap_url', models.CharField(blank=True, default='', max_length=200)),
                ('website', models.CharField(blank=True, default='', max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.item')),
            ],
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag2Item',
        ),
    ]
