# Generated by Django 5.1.4 on 2024-12-24 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('imgUrl', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('songUrl', models.CharField(max_length=200)),
                ('urlType', models.CharField(choices=[('SC', 'SoundCloud'), ('SP', 'Spotify'), ('YT', 'YouTube')], default='SC')),
                ('genre', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('gmap', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=5)),
                ('cuisine', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restaurant', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=420)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('website', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag2Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.music')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurant')),
                ('rfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurantfood')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.tag')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.travel')),
            ],
            options={
                'ordering': ['tag_id'],
            },
        ),
        migrations.CreateModel(
            name='Image2Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.image')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.music')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurant')),
                ('rfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurantfood')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.travel')),
            ],
            options={
                'ordering': ['image_id'],
            },
        ),
    ]
