# Generated by Django 5.1.4 on 2024-12-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image2item',
            old_name='image_id',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='image2item',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='image2item',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='image2item',
            old_name='rfood_id',
            new_name='rfood',
        ),
        migrations.RenameField(
            model_name='image2item',
            old_name='travel_id',
            new_name='travel',
        ),
        migrations.RenameField(
            model_name='tag2item',
            old_name='music_id',
            new_name='music',
        ),
        migrations.RenameField(
            model_name='tag2item',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='tag2item',
            old_name='rfood_id',
            new_name='rfood',
        ),
        migrations.RenameField(
            model_name='tag2item',
            old_name='tag_id',
            new_name='tag',
        ),
        migrations.RenameField(
            model_name='tag2item',
            old_name='travel_id',
            new_name='travel',
        ),
        migrations.AlterField(
            model_name='restaurantfood',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank.restaurant'),
        ),
    ]
