# Generated by Django 5.1.4 on 2024-12-26 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0003_alter_image2item_music_alter_image2item_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('gmap_url', models.CharField(max_length=200)),
                ('item_url', models.CharField(max_length=200)),
                ('price_range', models.CharField(choices=[('1', '$'), ('2', '$$'), ('3', '$$$'), ('4', '$$$$'), ('5', '$$$$$')], default='1')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('cuisine', models.CharField(max_length=200)),
                ('music_source', models.CharField(choices=[('SC', 'SoundCloud'), ('SP', 'Spotify'), ('YT', 'YouTube')], default='SC')),
                ('artist', models.CharField(max_length=200)),
                ('music_meta', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='music',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='music',
        ),
        migrations.RemoveField(
            model_name='restaurantfood',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='rfood',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='rfood',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='travel',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='imgUrl',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='image2item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.item'),
        ),
        migrations.AddField(
            model_name='tag2item',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_dank.item'),
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantFood',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
