# Generated by Django 5.1.4 on 2025-01-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0006_alter_item_music_source_alter_item_price_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', ''), ('Dining', 'Dining'), ('Food', 'Food'), ('Music', 'Music'), ('Travel', 'Travel')], default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.00, max_digits=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cuisine',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='gmap_url',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_url',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='music_meta',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
