# Generated by Django 5.1.4 on 2025-02-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0014_remove_image_description_remove_image_img_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image_variable',
        ),
        migrations.AddField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='img_url',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
