# Generated by Django 5.1.4 on 2025-02-13 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0019_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api_dank.item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ItemImages',
        ),
    ]
