# Generated by Django 5.1.4 on 2025-02-26 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0021_remove_tag2item_tag_remove_tag2item_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dining',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dining', to='api_dank.item'),
        ),
        migrations.AlterField(
            model_name='food',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='food', to='api_dank.item'),
        ),
        migrations.AlterField(
            model_name='media',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='api_dank.item'),
        ),
        migrations.AlterField(
            model_name='travel',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='api_dank.item'),
        ),
    ]
