# Generated by Django 5.1.4 on 2024-12-22 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('songUrl', models.CharField(max_length=200)),
                ('urlType', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['song'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=5)),
                ('cuisine', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=420)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('restaurant', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=420)),
                ('review', models.CharField(max_length=710)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('citystate', models.CharField(max_length=200)),
                ('photos', models.CharField(max_length=200)),
                ('rating', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag2Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank_bank.music')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank_bank.restaurant')),
                ('rfood_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank_bank.restaurantfood')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank_bank.tag')),
                ('travel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_dank_bank.travel')),
            ],
            options={
                'ordering': ['tag_id'],
            },
        ),
    ]
