# Generated by Django 5.1.6 on 2025-02-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0009_alter_item_price_range'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={},
        ),
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_variable',
            field=models.ImageField(default='{default_filename)', null=True, upload_to='uploads/'),
        ),
    ]
