# Generated by Django 5.1.4 on 2025-02-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0011_remove_image_image_variable_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='artist',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('', ''), ('Dining', 'Dining'), ('Food', 'Food'), ('Music', 'Music'), ('Travel', 'Travel')]),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='item',
            name='cuisine',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='gmap_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_url',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='music_meta',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='rating',
            field=models.IntegerField(default=50),
        ),
    ]
