# Generated by Django 5.1.4 on 2025-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0013_alter_image2item_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='description',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_url',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='image_variable',
            field=models.ImageField(default='{default_filename)', null=True, upload_to='uploads/'),
        ),
    ]
