# Generated by Django 5.1.4 on 2025-02-12 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0018_alter_itemimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['category', 'id']},
        ),
    ]
