# Generated by Django 5.1.4 on 2025-02-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank', '0022_alter_dining_item_alter_food_item_alter_media_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
