# Generated by Django 5.1.4 on 2024-12-24 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_dank_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image2item',
            name='image',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='music',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='rfood',
        ),
        migrations.RemoveField(
            model_name='image2item',
            name='travel',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='music',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='rfood',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tag2item',
            name='travel',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Image2Item',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='RestaurantFood',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag2Item',
        ),
        migrations.DeleteModel(
            name='Travel',
        ),
    ]
